---
- name: include os-specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- include: setup-redhat.yml
  when: ansible_os_family == "RedHat"

- name: set limits for elasticsearch
  template: >
    src=limits.conf.j2
    dest=/etc/security/limits.d/elasticsearch.conf
    owner=root
    group=root
    mode=0644

- name: template elasticsearch defaults
  template: >-
    src=elasticsearch.j2
    dest={{ elasticsearch_defaults_path }}
    owner=root
    group=root
    mode=0644
    backup=yes
  notify: restart elasticsearch

- name: template logging.yml
  template: >-
    src=logging.yml.j2
    dest=/etc/elasticsearch/logging.yml
    owner=root
    group=root
    mode=0644
    backup=yes
  notify: restart elasticsearch

- name: template elasticsearch.yml
  template: >-
    src=elasticsearch.yml.j2
    dest=/etc/elasticsearch/elasticsearch.yml
    owner=root
    group=root
    mode=0644
    backup=yes
  notify: restart elasticsearch

- name: install plugins
  command: >
    {{ elasticsearch_path_home }}/bin/plugin -install {{ item.path }}
    creates={{ elasticsearch_path_plugins }}/{{ item.name }}
  with_items: elasticsearch_plugins

- name: enable and start elasticsearch
  service: name=elasticsearch enabled=yes state=started
